# Generated by Django 3.1.7 on 2021-04-05 08:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tclone', '0002_auto_20210318_0943'),
    ]

    operations = [
        migrations.CreateModel(
            name='FF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ff_followed', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ff_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'followed')},
            },
        ),
        migrations.DeleteModel(
            name='Tweet',
        ),
    ]
